<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>appicon_background.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CP.Client.Core" Version="0.1.47" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.2" />
      <PackageReference Include="Spectre.Console" Version="0.54.0" />
      <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Scripts\API-Deploy.ps1">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Scripts\Laa-Build.ps1">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Scripts\Laa-Deploy.ps1">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Scripts\API-Build.ps1">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Scripts\publish-local-nuget.ps1">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Scripts\Swap-ProdDbToDev.ps1">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Scripts\Restore-DevDb.ps1">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="appicon_background.ico" />
      <Resource Include="appicon_background.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

</Project>
